before_script:
  - node --version; npm --version; yarn --version
  - ls -la
  - yarn config set cache-folder /gitlab.cache/.yarn
  - PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org yarn install --prefer-offline
  - IMAGE_TAG=$(echo $CI_COMMIT_SHA | cut -c 1-7)
  - echo ${IMAGE_TAG}

.cache_test: &cache_test
  cache:
    key: "$CI_PROJECT_PATH-$CI_PROJECT_ID-test"
  tags:
    - node8

.cache_publish: &cache_publish
  cache:
    key: "$CI_PROJECT_PATH-$CI_PROJECT_ID-build"
  tags:
    - node8

stages:
  - test
  - publish

test:
  <<: *cache_test
  stage: test
  script:
    - yarn test
    - yarn lint

publish:
  <<: *cache_publish
  stage: publish
  only:
    - /^v?\d+\.\d+\.\d+(?:-(alpha|beta)\.\d+)?$/
  script:
    - echo "$CNPMRC" > ~/.npmrc
    - yarn build
    - yarn cnpm
